### ISSUE TITLE
file does not exist but it clearly does.

### ISSUE THREAD

**Issue by Drunkenpanda2000** [Bluedrack28/vscode-wal#2]
Below you an find my console.

```
[drunkenpanda@Diablo wal]$ wal -R -i ~/Downloads/darkesthouer.png 
[I] image: Using image darkesthouer.png.
[I] colors: Found cached colorscheme.
[I] theme: Set theme to colors.json.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.

                                
                                

Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.1.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 198, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 175, in parse_args
    export.every(colors_plain)
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 63, in every
    template(colors, file.path, join(output_dir, file.name))
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 17, in template
    util.save_file(template_data, output_file)
  File "/usr/lib/python3.7/site-packages/pywal/util.py", line 77, in save_file
    with open(export_file, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/drunkenpanda/.cache/wal/colors-vscode-theme.json'
[drunkenpanda@Diablo wal]$ ls
colors			    colors-sway		      colors-wal.vim	 colors.yml
colors-konsole.colorscheme  colors-tty.sh	      colors.Xresources  schemes
colors-oomox		    colors-vscode-theme.json  colors.css	 sequences
colors-putty.reg	    colors-wal-dwm.h	      colors.json	 wal
colors-rofi-dark.rasi	    colors-wal-st.h	      colors.scss
colors-rofi-light.rasi	    colors-wal-tabbed.h       colors.sh
[drunkenpanda@Diablo wal]$ 
```

**Comment by rugglcon** [comment]
You need to make the original file not a symlink. I had this same problem, just delete the file and create it again as a regular file
